/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 2022_cavallo_daytona_sp3.glb --transform 
Files: 2022_cavallo_daytona_sp3.glb [43.33MB] > /home/sayansinha/project/portfolio/8/sayanos/public/models/2022_cavallo_daytona_sp3-transformed.glb [4.43MB] (90%)
Author: DisneyCars (https://sketchfab.com/supercarmodels)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/2022-cavallo-daytona-sp3-29ba4beba44f461a8234143fd092d24a
Title: 2022 Cavallo Daytona SP3
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/2022_cavallo_daytona_sp3-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Material2.geometry} material={materials.PaletteMaterial001} rotation={[-Math.PI / 2, 0, 0]} scale={0.054} />
      <mesh geometry={nodes.Material2_1.geometry} material={materials['022_Ferrari_Daytona_SP3_FerrariBadge']} rotation={[-Math.PI / 2, 0, 0]} scale={0.054} />
      <mesh geometry={nodes.Material2_2.geometry} material={materials.PaletteMaterial002} rotation={[-Math.PI / 2, 0, 0]} scale={0.054} />
      <mesh geometry={nodes.Material2_3.geometry} material={materials.PaletteMaterial003} rotation={[-Math.PI / 2, 0, 0]} scale={0.054} />
      <mesh geometry={nodes.Material2_4.geometry} material={materials['022_Ferrari_Daytona_SP3_Stitching']} rotation={[-Math.PI / 2, 0, 0]} scale={0.054} />
      <mesh geometry={nodes.Material2_5.geometry} material={materials['022_Ferrari_Daytona_SP3_Icons']} rotation={[-Math.PI / 2, 0, 0]} scale={0.054} />
      <mesh geometry={nodes.Material2_6.geometry} material={materials['022_Ferrari_Daytona_SP3_Speakers']} rotation={[-Math.PI / 2, 0, 0]} scale={0.054} />
      <mesh geometry={nodes.Material3.geometry} material={materials['022_Ferrari_Daytona_SP3_BlackSeats_0']} rotation={[-Math.PI / 2, 0, 0]} scale={0.054} />
      <mesh geometry={nodes.Material2_7.geometry} material={materials['022_Ferrari_Daytona_SP3_wheel_001']} rotation={[-Math.PI / 2, 0, 0]} scale={0.054} />
      <mesh geometry={nodes.Material2_8.geometry} material={materials['022_Ferrari_Daytona_SP3_v_ext_ferrari_bonnet']} rotation={[-Math.PI / 2, 0, 0]} scale={0.054} />
      <mesh geometry={nodes.Material2_9.geometry} material={materials['022_Ferrari_Daytona_SP3_v_int_display']} rotation={[-Math.PI / 2, 0, 0]} scale={0.054} />
      <mesh geometry={nodes.Material2_10.geometry} material={materials['022_Ferrari_Daytona_SP3_f_int_belt_sticker']} rotation={[-Math.PI / 2, 0, 0]} scale={0.054} />
      <mesh geometry={nodes.Material2_11.geometry} material={materials['022_Ferrari_Daytona_SP3_RimBadges1']} rotation={[-Math.PI / 2, 0, 0]} scale={0.054} />
      <mesh geometry={nodes.Material2_12.geometry} material={materials['022_Ferrari_Daytona_SP3_CalipersBadge']} rotation={[-Math.PI / 2, 0, 0]} scale={0.054} />
      <mesh geometry={nodes.Material2_13.geometry} material={materials['022_Ferrari_Daytona_SP3_BrakesRotors']} rotation={[-Math.PI / 2, 0, 0]} scale={0.054} />
      <mesh geometry={nodes.Material3_1.geometry} material={materials['022_Ferrari_Daytona_SP3_Grille1_1']} rotation={[-Math.PI / 2, 0, 0]} scale={0.054} />
      <mesh geometry={nodes.Material2_14.geometry} material={materials['022_Ferrari_Daytona_SP3_Grille1']} rotation={[-Math.PI / 2, 0, 0]} scale={0.054} />
      <mesh geometry={nodes.Material3_2.geometry} material={materials['022_Ferrari_Daytona_SP3_file12Material_2']} rotation={[-Math.PI / 2, 0, 0]} scale={0.054} />
      <mesh geometry={nodes.Material2_15.geometry} material={materials['022_Ferrari_Daytona_SP3_file12Material']} rotation={[-Math.PI / 2, 0, 0]} scale={0.054} />
      <mesh geometry={nodes.Material2_16.geometry} material={materials.PaletteMaterial004} rotation={[-Math.PI / 2, 0, 0]} scale={0.054} />
      <mesh geometry={nodes.Material2_17.geometry} material={materials.material} rotation={[-Math.PI / 2, 0, 0]} scale={0.054} />
    </group>
  )
}

useGLTF.preload('/2022_cavallo_daytona_sp3-transformed.glb')
