/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 asus_pc_gaming_monitor.glb --transform 
Files: asus_pc_gaming_monitor.glb [1.13MB] > /home/sayansinha/project/portfolio/8/sayanos/public/models/asus_pc_gaming_monitor-transformed.glb [50.27KB] (96%)
Author: Artik (https://sketchfab.com/artikdev)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/asus-pc-gaming-monitor-941ce968c30a42d0a640a5c9d7f56128
Title: Asus PC Gaming Monitor
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/asus_pc_gaming_monitor-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plano_Base_0.geometry} material={materials.Base} rotation={[-Math.PI / 2, 0, 0]} scale={0.065} />
      <mesh geometry={nodes.Plano001_Screen_0.geometry} material={materials.Screen} position={[0, 0.233, -0.164]} scale={0.065} />
      <mesh geometry={nodes.Plano001_Backboard_0.geometry} material={materials.Backboard} position={[0, 0.233, -0.164]} scale={0.065} />
      <mesh geometry={nodes.Bolt_Bolt_0.geometry} material={materials.Bolt} position={[0.09, 0.269, -0.115]} scale={0.004} />
    </group>
  )
}

useGLTF.preload('/asus_pc_gaming_monitor-transformed.glb')
