/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 banana_plant_with_pot.glb --transform 
Files: banana_plant_with_pot.glb [2.45MB] > /home/sayansinha/project/portfolio/8/sayanos/public/models/banana_plant_with_pot-transformed.glb [482.69KB] (80%)
Author: GobyDiputra (https://sketchfab.com/GobyDiputra)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/banana-plant-with-pot-789d665f88704393af11a1b64956d474
Title: Banana Plant With Pot
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/banana_plant_with_pot-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_5.geometry} material={materials.material} position={[0.021, 0.114, 0.246]} rotation={[Math.PI / 2, 0, -0.044]} scale={[-0.019, 0.019, 0.019]} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.material_1} position={[0.021, 0.114, 0.246]} rotation={[Math.PI / 2, 0, -0.044]} scale={[-0.019, 0.019, 0.019]} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.material_2} position={[-0.052, 1.244, -0.133]} rotation={[1.378, -0.045, 1.897]} scale={[-0.044, 0.044, 0.045]} />
      <mesh geometry={nodes.Object_9.geometry} material={materials.material_3} position={[-0.052, 1.244, -0.133]} rotation={[1.378, -0.045, 1.897]} scale={[-0.044, 0.044, 0.045]} />
      <mesh geometry={nodes.Object_10.geometry} material={materials.material_4} position={[-0.052, 1.244, -0.133]} rotation={[1.378, -0.045, 1.897]} scale={[-0.044, 0.044, 0.045]} />
    </group>
  )
}

useGLTF.preload('/banana_plant_with_pot-transformed.glb')
