/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 bookcase.glb --transform 
Files: bookcase.glb [8.67MB] > /home/sayansinha/project/portfolio/8/sayanos/public/models/bookcase-transformed.glb [1.24MB] (86%)
Author: 3D_for_everyone (https://sketchfab.com/boglarka4)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/bookcase-eac9c98de25c429a9f5df719ac2fb261
Title: Bookcase
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/bookcase-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Shelf_frame_Shelf_frame_0.geometry} material={materials.Shelf_frame} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Shelf_1_Shelf_0.geometry} material={materials.Shelf} position={[0, 1.605, 0.101]} rotation={[-Math.PI / 2, 0, 0]} scale={0.2} />
      <mesh geometry={nodes.Book_1_Book_1_0.geometry} material={materials.Book_1} position={[0.07, 1.17, 0.019]} rotation={[-1.361, 0, 0]} scale={1.217} />
      <mesh geometry={nodes.Book_1_Book_1_paper_0.geometry} material={materials.Book_1_paper} position={[0.07, 1.17, 0.019]} rotation={[-1.361, 0, 0]} scale={1.217} />
      <mesh geometry={nodes.Book_2_Book_2_0.geometry} material={materials.Book_2} position={[0.081, 1.484, 0.094]} rotation={[0, -0.199, 0]} scale={1.246} />
      <mesh geometry={nodes.Book_3_Book_3_0.geometry} material={materials.Book_3} position={[0.11, 0.646, 0.107]} rotation={[0, -0.099, 0]} scale={1.505} />
      <mesh geometry={nodes.Book_4_Book_4_0.geometry} material={materials.Book_4} position={[0.063, 0.709, 0.063]} rotation={[0, 0.246, 0]} scale={1.236} />
      <mesh geometry={nodes.Book_5_Book_5_0.geometry} material={materials.Book_5} position={[0.039, 1.171, -0.032]} rotation={[-1.355, 0, 0]} scale={1.361} />
      <mesh geometry={nodes.Book_6_Book_6_0.geometry} material={materials.Book_6} position={[0.116, 0.361, 0.004]} rotation={[-1.487, 0, 0]} scale={1.935} />
      <mesh geometry={nodes.Book_6_Book_6_paper_0.geometry} material={materials.Book_6_paper} position={[0.116, 0.361, 0.004]} rotation={[-1.487, 0, 0]} scale={1.935} />
      <mesh geometry={nodes.Book_7_Book_7_0.geometry} material={materials.Book_7} position={[0.097, 0.383, 0.052]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.353, 1.036, 1.353]} />
      <mesh geometry={nodes.Book_8_Book_8_0.geometry} material={materials.Book_8} position={[0.061, 0.364, -0.18]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.439, 1.886, 1.322]} />
      <mesh geometry={nodes.Book_9_Book_9_0.geometry} material={materials.Book_9} position={[0.078, 1.509, 0.088]} scale={[1.343, 2.54, 1.447]} />
      <mesh geometry={nodes.Book_10_Book_10_0.geometry} material={materials.Book_10} position={[0.057, 1.147, -0.102]} rotation={[-1.291, 0, 0]} scale={1.157} />
      <mesh geometry={nodes.Book_11_Book_11_0.geometry} material={materials.Book_11} position={[0.059, 1.176, -0.252]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.306, 1, 1.306]} />
      <mesh geometry={nodes.Book_12_Book_12_0.geometry} material={materials.Book_12} position={[0.054, 0.357, -0.114]} rotation={[-1.748, 0, 0]} scale={1.314} />
      <mesh geometry={nodes.Book_13_Book_13_0.geometry} material={materials.Book_13} position={[0.057, 1.134, -0.208]} rotation={[-1.66, 0, 0]} scale={1.558} />
      <mesh geometry={nodes.Book_14_Book_14_0.geometry} material={materials.Book_14} position={[0.079, 1.447, 0.095]} scale={1.246} />
      <mesh geometry={nodes.Book_15_Book_15_0.geometry} material={materials.Book_15} position={[0.024, 1.163, -0.063]} rotation={[-1.345, 0, 0]} scale={1.286} />
      <mesh geometry={nodes.Book_16_Book_16_0.geometry} material={materials.Book_16} position={[0.069, 0.686, 0.108]} rotation={[0, -0.179, 0]} scale={1.371} />
      <mesh geometry={nodes.Book_16_Book_16_paper_0.geometry} material={materials.Book_16_paper} position={[0.069, 0.686, 0.108]} rotation={[0, -0.179, 0]} scale={1.371} />
      <mesh geometry={nodes.Book_17_Book_17_0.geometry} material={materials.Book_17} position={[0.085, 0.379, -0.24]} rotation={[-Math.PI / 2, 0, 0]} scale={1.322} />
    </group>
  )
}

useGLTF.preload('/bookcase-transformed.glb')
