/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 shelby_cobra__www.vecarz.com.glb --transform 
Files: shelby_cobra__www.vecarz.com.glb [17.77MB] > /home/sayansinha/project/portfolio/8/sayanos/public/models/shelby_cobra__www.vecarz.com-transformed.glb [1.5MB] (92%)
Author: vecarz (https://sketchfab.com/heynic)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/shelby-cobra-wwwvecarzcom-a9024d1c23f1490f8f40468946c14b0c
Title: Shelby Cobra | www.vecarz.com
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/shelby_cobra__www.vecarz.com-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_8.geometry} material={materials.PaletteMaterial001} position={[3.316, 0.573, 1.127]} rotation={[0, 0, -0.378]} scale={[0.273, 0.273, 0.385]} />
      <mesh geometry={nodes.Object_11.geometry} material={materials.PaletteMaterial002} position={[3.316, 0.573, 1.127]} rotation={[-Math.PI / 2, -1.239, 0]} scale={0.249} />
      <mesh geometry={nodes.Object_13.geometry} material={materials.PaletteMaterial003} position={[3.316, 0.573, 1.127]} rotation={[-Math.PI / 2, -1.239, 0]} scale={0.249} />
      <mesh geometry={nodes.Object_35.geometry} material={materials.PaletteMaterial004} position={[2.608, 0.749, -0.581]} rotation={[-Math.PI / 2, 0.143, 0]} scale={[0.36, 0.36, 0.288]} />
      <mesh geometry={nodes.Object_76.geometry} material={materials.PaletteMaterial005} position={[4.697, 0.877, -1.02]} rotation={[-Math.PI / 2, -0.005, 0]} scale={0.031} />
      <mesh geometry={nodes.Object_94.geometry} material={materials.PaletteMaterial006} position={[1.666, 1.171, 0.497]} rotation={[-Math.PI / 2, 1.304, Math.PI / 2]} scale={0.261} />
      <mesh geometry={nodes.Object_118.geometry} material={materials.PaletteMaterial007} position={[0.026, -0.102, 0]} rotation={[-Math.PI / 2, -0.005, 0]} scale={[1, 1, 0.998]} />
      <mesh geometry={nodes.Object_135.geometry} material={materials.PaletteMaterial008} position={[-0.195, -0.215, 0]} rotation={[-Math.PI / 2, -0.005, 0]} />
      <mesh geometry={nodes.Object_152.geometry} material={materials.Lamp} position={[0.003, -0.091, 0]} rotation={[-Math.PI / 2, -0.005, 0]} />
      <mesh geometry={nodes.Object_155.geometry} material={materials.PaletteMaterial009} position={[0.003, -0.091, 0]} rotation={[-Math.PI / 2, -0.005, 0]} />
      <mesh geometry={nodes.Object_32.geometry} material={materials.Cuire} position={[2.608, 0.749, -0.581]} rotation={[-Math.PI / 2, 0.143, 0]} scale={[0.36, 0.36, 0.288]} />
      <mesh geometry={nodes.Object_96.geometry} material={materials.Leather_volant} position={[1.666, 1.171, 0.497]} rotation={[-Math.PI / 2, 1.304, Math.PI / 2]} scale={0.261} />
    </group>
  )
}

useGLTF.preload('/shelby_cobra__www.vecarz.com-transformed.glb')
