/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 cushion_chair.glb --transform 
Files: cushion_chair.glb [1.37MB] > /home/sayansinha/project/portfolio/8/sayanos/public/models/cushion_chair-transformed.glb [101.37KB] (93%)
Author: Ayomiposi (https://sketchfab.com/Ayomiposi)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cushion-chair-ce53415502de41e699d6a3cd5def8065
Title: Cushion Chair
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/cushion_chair-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube_Material_0.geometry} material={materials.Material} position={[0, 2.239, 0]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cylinder_Material001_0.geometry} material={materials['Material.001']} position={[0, 0.918, -0.166]} rotation={[-Math.PI / 2, 0, 0]} scale={0.087} />
    </group>
  )
}

useGLTF.preload('/cushion_chair-transformed.glb')
