/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 custom_-_mechanical_keyboard.glb --transform 
Files: custom_-_mechanical_keyboard.glb [11.28MB] > /home/sayansinha/project/portfolio/8/sayanos/public/models/custom_-_mechanical_keyboard-transformed.glb [431.02KB] (96%)
Author: unknown.fbx (https://sketchfab.com/unknown.fbx)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/custom-mechanical-keyboard-90d61eec0c484332ab562c5f4eda6f52
Title: Custom - Mechanical Keyboard
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/custom_-_mechanical_keyboard-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.defaultMaterial.geometry} material={materials.Keyboard} position={[0, -23.907, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.defaultMaterial_1.geometry} material={materials.Wood_00} position={[0, -23.907, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
    </group>
  )
}

useGLTF.preload('/custom_-_mechanical_keyboard-transformed.glb')
