/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 gaming_cpu.glb --transform 
Files: gaming_cpu.glb [3.19MB] > /home/sayansinha/project/portfolio/8/sayanos/public/models/gaming_cpu-transformed.glb [256.96KB] (92%)
Author: DeimonIC93 (https://sketchfab.com/Deimon)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/gaming-cpu-0c8e8fe5fc9442788a205cb52908f2b6
Title: GAMING CPU
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/gaming_cpu-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.PaletteMaterial001} position={[0.406, 2.64, 0]} rotation={[0, 0, -Math.PI / 2]} scale={[2.148, 1, 1]} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.PaletteMaterial002} position={[0.406, 2.64, 0]} rotation={[0, 0, -Math.PI / 2]} scale={[2.148, 1, 1]} />
      <mesh geometry={nodes.Object_14.geometry} material={materials.cpupic} position={[-3.271, 2.195, 0.049]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.198, 1.204, 1.659]} />
    </group>
  )
}

useGLTF.preload('/gaming_cpu-transformed.glb')
