/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 gaming_headset.glb --transform 
Files: gaming_headset.glb [16.51MB] > /home/sayansinha/project/portfolio/8/sayanos/public/models/gaming_headset-transformed.glb [1.01MB] (94%)
Author: YarikLegendary (https://sketchfab.com/YarikLegendary)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/gaming-headset-8a8ea478c4ec40bfad58f9e214177bdc
Title: Gaming Headset
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/gaming_headset-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.PaletteMaterial001} rotation={[3.134, 0, 0]} />
      <mesh geometry={nodes.Object_9.geometry} material={materials.PaletteMaterial002} rotation={[3.134, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/gaming_headset-transformed.glb')
