/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 hanging_led_lamp.glb --transform 
Files: hanging_led_lamp.glb [578.26KB] > /home/sayansinha/project/portfolio/8/sayanos/public/models/hanging_led_lamp-transformed.glb [37.62KB] (93%)
Author: Jopa Shnik (https://sketchfab.com/golovashenco_dima)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/hanging-led-lamp-3e10c56d38de491d958285db17549251
Title: Hanging LED Lamp
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/hanging_led_lamp-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.lamp_metal_0.geometry} material={materials.metal} rotation={[-Math.PI / 2, 0, 0]} scale={1.759} />
      <mesh geometry={nodes.lamp_light_0.geometry} material={materials.light} rotation={[-Math.PI / 2, 0, 0]} scale={1.759} />
      <mesh geometry={nodes.lamp_1_0.geometry} material={materials.material} rotation={[-Math.PI / 2, 0, 0]} scale={1.759} />
      <mesh geometry={nodes.Cylinder_2_0.geometry} material={materials.material_3} position={[0, 1.201, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={1.759} />
    </group>
  )
}

useGLTF.preload('/hanging_led_lamp-transformed.glb')
