/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 krk_classic_5_studio_monitor_speaker.glb --transform 
Files: krk_classic_5_studio_monitor_speaker.glb [68.66MB] > /home/sayansinha/project/portfolio/8/sayanos/public/models/krk_classic_5_studio_monitor_speaker-transformed.glb [6.41MB] (91%)
Author: TheGiwi (https://sketchfab.com/TheGiwi)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/krk-classic-5-studio-monitor-speaker-5c03f6b1082a4decb33ae7511209271a
Title: KRK Classic 5 Studio Monitor Speaker
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/krk_classic_5_studio_monitor_speaker-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.PaletteMaterial001} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_3.geometry} material={materials.Front_driver} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_4.geometry} material={materials['Front_driver_yellow.001']} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_5.geometry} material={materials.Front_material} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.Front_material_face} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_7.geometry} material={materials.Front_tweeter} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.Middle_material} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_9.geometry} material={materials.Plastic_noisy_brwn} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_10.geometry} material={materials.Plastic_smooth_xlr} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_13.geometry} material={materials.Plastic_noisy_blk} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_14.geometry} material={materials['Plastic_noisy_blk.001']} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_17.geometry} material={materials.Plastic_smooth_vol} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_19.geometry} material={materials.Speaker_back} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/krk_classic_5_studio_monitor_speaker-transformed.glb')
