/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 lord_krishna_playing_the_flute_at_csmvs.glb --transform 
Files: lord_krishna_playing_the_flute_at_csmvs.glb [11.47MB] > /home/sayansinha/project/portfolio/8/sayanos/public/models/lord_krishna_playing_the_flute_at_csmvs-transformed.glb [567.86KB] (95%)
Author: raobott (https://sketchfab.com/raobott)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/lord-krishna-playing-the-flute-at-csmvs-bb600f4f3a7943738f9b1a616e22c85a
Title: Lord Krishna playing the flute at CSMVS
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/lord_krishna_playing_the_flute_at_csmvs-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.main} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/lord_krishna_playing_the_flute_at_csmvs-transformed.glb')
