/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 monstera_deliciosa_potted_mid-century_plant.glb --transform 
Files: monstera_deliciosa_potted_mid-century_plant.glb [8.19MB] > /home/sayansinha/project/portfolio/8/sayanos/public/models/monstera_deliciosa_potted_mid-century_plant-transformed.glb [856.24KB] (90%)
Author: Giora (https://sketchfab.com/ChubbyPanda)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/monstera-deliciosa-potted-mid-century-plant-1ab9bf841df04c07b1819be596327629
Title: Monstera Deliciosa Potted Mid-Century plant
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/monstera_deliciosa_potted_mid-century_plant-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.root_HP_1_Mat2_0.geometry} material={materials['Mat.2']} position={[0.001, 0.001, 0.002]} scale={0.009} />
      <mesh geometry={nodes.Leaves_Mat1_0.geometry} material={materials['Mat.1']} position={[0.04, 0.468, -0.042]} scale={0.009} />
      <mesh geometry={nodes.Stand_Mat_0.geometry} material={materials.material} position={[0, 0.021, 0.065]} scale={0.009} />
    </group>
  )
}

useGLTF.preload('/monstera_deliciosa_potted_mid-century_plant-transformed.glb')
