/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 mouse_a4tech_x-710bk.glb --transform 
Files: mouse_a4tech_x-710bk.glb [7.71MB] > /home/sayansinha/project/portfolio/8/sayanos/public/models/mouse_a4tech_x-710bk-transformed.glb [714.62KB] (91%)
Author: I1San (https://sketchfab.com/ivanSan96)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mouse-a4tech-x-710bk-f496168739384cdb86ef6d65e2068a3f
Title: Mouse A4Tech X-710BK
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/mouse_a4tech_x-710bk-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mouse_6_Material_base_0.geometry} material={materials.Material_base} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/mouse_a4tech_x-710bk-transformed.glb')
