/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 nasa_mug.glb --transform 
Files: nasa_mug.glb [1.23MB] > /home/sayansinha/project/portfolio/8/sayanos/public/models/nasa_mug-transformed.glb [107.95KB] (91%)
Author: TheoClarke (https://sketchfab.com/TheoClarke)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/nasa-mug-8e22a734f2204c1dacc26f4fafe7d17e
Title: NASA Mug 🚀
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/nasa_mug-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.polySurface78_phong10_0.geometry} material={materials.phong10} position={[0.379, 0.042, -0.379]} scale={0.006} />
    </group>
  )
}

useGLTF.preload('/nasa_mug-transformed.glb')
