/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 persian_carpet.glb --transform 
Files: persian_carpet.glb [11.7MB] > /home/sayansinha/project/portfolio/8/sayanos/public/models/persian_carpet-transformed.glb [1.22MB] (90%)
Author: ChoboiAssets (https://sketchfab.com/alsoliman905)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/persian-carpet-4592468c03784f0d895876ec670de1cd
Title: Persian carpet
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/persian_carpet-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane001_Material001_0.geometry} material={materials['Material.001']} rotation={[-Math.PI / 2, 0, 0]} scale={[1, 1.547, 1]} />
    </group>
  )
}

useGLTF.preload('/persian_carpet-transformed.glb')
