/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 plant_pot_ivy.glb --transform 
Files: plant_pot_ivy.glb [5.7MB] > /home/sayansinha/project/portfolio/8/sayanos/public/models/plant_pot_ivy-transformed.glb [443.15KB] (92%)
Author: anybody (https://sketchfab.com/anybody)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/plant-pot-ivy-507dae90a1f541e0a3e2ccbee5abc333
Title: Plant Pot Ivy
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/plant_pot_ivy-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials['Material.019']} position={[0, 0, 0.013]} rotation={[Math.PI, -1.141, Math.PI]} scale={0.475} />
      <mesh geometry={nodes.Object_5.geometry} material={materials['Material.018']} position={[0, 0, 0.013]} rotation={[Math.PI, -1.141, Math.PI]} scale={0.475} />
      <mesh geometry={nodes.Object_7.geometry} material={materials['Material.017']} scale={1.107} />
      <mesh geometry={nodes.Object_9.geometry} material={materials['Material.016']} position={[0.07, 0.216, 0.094]} rotation={[-1.568, -0.096, -1.544]} scale={1.107} />
    </group>
  )
}

useGLTF.preload('/plant_pot_ivy-transformed.glb')
