/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 silver_crest_gaming_mousepad.glb --transform 
Files: silver_crest_gaming_mousepad.glb [219.76KB] > /home/sayansinha/project/portfolio/8/sayanos/public/models/silver_crest_gaming_mousepad-transformed.glb [24.29KB] (89%)
Author: Cymen05 (https://sketchfab.com/Cymen05)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/silver-crest-gaming-mousepad-8c551e4f6bf248db99aa77a3d0221497
Title: Silver Crest Gaming Mousepad
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/silver_crest_gaming_mousepad-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mousepad_Mousepad_0.geometry} material={materials.Mousepad} position={[698.702, 82.695, -249.326]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
    </group>
  )
}

useGLTF.preload('/silver_crest_gaming_mousepad-transformed.glb')
