/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 steampunk-style_clock.glb --transform 
Files: steampunk-style_clock.glb [12.3MB] > /home/sayansinha/project/portfolio/8/sayanos/public/models/steampunk-style_clock-transformed.glb [597.4KB] (95%)
Author: sandeep Vaghela (https://sketchfab.com/sandeep.vaghela)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/steampunk-style-clock-1637fd58c4b441b4b1ed44c5448406e1
Title: Steampunk-Style Clock
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/steampunk-style_clock-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cover_Clock_Mat_01_0.geometry} material={materials.Clock_Mat_01} scale={0.01} />
      <mesh geometry={nodes.Glass_Glass_Mat_0.geometry} material={materials.Glass_Mat} scale={0.01} />
      <mesh geometry={nodes.polySurface43_Clock_Mat_02_0.geometry} material={materials.Clock_Mat_02} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/steampunk-style_clock-transformed.glb')
