/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 support_casque.glb --transform 
Files: support_casque.glb [80.97KB] > /home/sayansinha/project/portfolio/8/sayanos/public/models/support_casque-transformed.glb [7.17KB] (91%)
Author: punk__85 (https://sketchfab.com/punk1085)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/support-casque-ad02e0e9716d419d92b080a8542a3dcd
Title: Support Casque
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/support_casque-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['Cube001_Mat��riau_0'].geometry} material={materials.Matriau} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['Cube001_Mat��riau002_0'].geometry} material={materials['Matriau.002']} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['Cube001_Mat��riau001_0'].geometry} material={materials['Matriau.001']} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/support_casque-transformed.glb')
